In [1]:
import numpy as np

In [4]:
# 1. A 1D array of numbers from 0 to 9
arr1 = np.arange(10)

# 2. A 2D array of shape (3, 4) filled with zeros
arr2 = np.zeros((3, 4))

# 3. A 3x3 identity matrix
arr3 = np.eye(3)

# 4. A 1D array of 10 equally spaced values between 1 and 100
arr4 = np.linspace(1, 100, 10)

# 5. A 3x3 array with random integers between 10 and 50
arr5 = np.random.randint(10, 51, size=(3, 3))

print(arr1, arr2, arr3, arr4, arr5, sep="\n\n")


[0 1 2 3 4 5 6 7 8 9]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]

[[37 42 13]
 [46 23 27]
 [12 47 43]]


In [5]:
arr3d = np.random.random((2, 3, 4))

print("Number of dimensions:", arr3d.ndim)
print("Shape:", arr3d.shape)
print("Total number of elements:", arr3d.size)
print("Data type:", arr3d.dtype)
print("Size of each element (bytes):", arr3d.itemsize)
print("Total memory consumed (bytes):", arr3d.nbytes)

Number of dimensions: 3
Shape: (2, 3, 4)
Total number of elements: 24
Data type: float64
Size of each element (bytes): 8
Total memory consumed (bytes): 192


In [8]:
arr = np.arange(0, 20)

print("First element:", arr[0])
print("Last element:", arr[-1])
print("Middle element:", arr[len(arr)//2])
print("Elements from index 5 to 15:", arr[5:15])
print("Even numbers:", arr[0::2])
print("Reversed array:", arr[::-1])

First element: 0
Last element: 19
Middle element: 10
Elements from index 5 to 15: [ 5  6  7  8  9 10 11 12 13 14]
Even numbers: [ 0  2  4  6  8 10 12 14 16 18]
Reversed array: [19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [14]:
arr2d = np.arange(1, 26).reshape(5, 5)


print("Array:\n", arr2d)
print("Element at row 2, column 3:", arr2d[1, 2])
print("Third row:", arr2d[2])
print("Second column:", arr2d[:, 1])
print("3x3 center sub-matrix:\n", arr2d[1:4, 1:4])

arr2d[-1, :] = 0
arr2d[:, 0] = -1

print("Modified Array:\n", arr2d)

Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Element at row 2, column 3: 8
Third row: [11 12 13 14 15]
Second column: [ 2  7 12 17 22]
3x3 center sub-matrix:
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]
Modified Array:
 [[-1  2  3  4  5]
 [-1  7  8  9 10]
 [-1 12 13 14 15]
 [-1 17 18 19 20]
 [-1  0  0  0  0]]


In [27]:
arr_random = np.random.randint(1, 51, size=15)

print("Array: ", arr_random)

print("Selected indices [1,3,5,7]:", arr_random[[1, 3, 5, 7]])
print("Elements> 25:", arr_random[arr_random > 25])

arr_random[arr_random < 10] = 10
print("Replace all values less than 10 with 10:", arr_random)

count_20_40 = np.sum((arr_random >= 20) & (arr_random <= 40))
print("Count of values between 20 and 40:", count_20_40)

print("Odd numbers:", arr_random[arr_random % 2 != 0])

Array:  [21 11 22 41 39 42 36 49 44 48 36 36  3 26 34]
Selected indices [1,3,5,7]: [11 41 42 49]
Elements> 25: [41 39 42 36 49 44 48 36 36 26 34]
Replace all values less than 10 with 10: [21 11 22 41 39 42 36 49 44 48 36 36 10 26 34]
Count of values between 20 and 40: 8
Odd numbers: [21 11 41 39 49]
